//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULARIOS_AVALADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMULARIOS_AVALADOS()
        {
            this.FORMULARIOS_TIEMPO = new HashSet<FORMULARIOS_TIEMPO>();
        }
    
        public int idFormularioAvalado { get; set; }
        public int idSolicitud { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public string Mes { get; set; }
        public int TotalHoras { get; set; }
        public string RutaArchivo { get; set; }
        public bool Estado { get; set; }
    
        public virtual SOLICITUD_TAREAS SOLICITUD_TAREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMULARIOS_TIEMPO> FORMULARIOS_TIEMPO { get; set; }
    }
}
