//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULARIOS_TIEMPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMULARIOS_TIEMPO()
        {
            this.FORMULARIOS_PAGO = new HashSet<FORMULARIOS_PAGO>();
        }
    
        public int idFormularioTiempo { get; set; }
        public int idFormularioAvalado { get; set; }
        public int HorasValidas { get; set; }
        public string QUINCENA { get; set; }
    
        public virtual FORMULARIOS_AVALADOS FORMULARIOS_AVALADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMULARIOS_PAGO> FORMULARIOS_PAGO { get; set; }
    }
}
