//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULARIOS_AVALADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMULARIOS_AVALADOS()
        {
            this.FORMULARIOS_TIEMPO = new HashSet<FORMULARIOS_TIEMPO>();
        }
    
        public int idFormularioAvalado { get; set; }
        public int idSolicitud { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public string Mes { get; set; }
        public int TotalHoras { get; set; }
        public string RutaArchivo { get; set; }
        public bool Estado { get; set; }
    
        public virtual SOLICITUD_TAREAS SOLICITUD_TAREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMULARIOS_TIEMPO> FORMULARIOS_TIEMPO { get; set; }
    }
}
