//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HorasExtraEntities : DbContext
    {
        public HorasExtraEntities()
            : base("name=HorasExtraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTAMENTOS> DEPARTAMENTOS { get; set; }
        public virtual DbSet<EVIDENCIAS> EVIDENCIAS { get; set; }
        public virtual DbSet<FORMULARIOS_AVALADOS> FORMULARIOS_AVALADOS { get; set; }
        public virtual DbSet<FORMULARIOS_PAGO> FORMULARIOS_PAGO { get; set; }
        public virtual DbSet<FORMULARIOS_TIEMPO> FORMULARIOS_TIEMPO { get; set; }
        public virtual DbSet<JORNADAS> JORNADAS { get; set; }
        public virtual DbSet<PAGOS> PAGOS { get; set; }
        public virtual DbSet<PERSONAS> PERSONAS { get; set; }
        public virtual DbSet<SOLICITUD_TAREAS> SOLICITUD_TAREAS { get; set; }
        public virtual DbSet<TIPOSPAGO> TIPOSPAGO { get; set; }
        public virtual DbSet<TareaPersona> TareaPersona { get; set; }
        public virtual DbSet<FormulariosSolcitudPersona> FormulariosSolcitudPersona { get; set; }
        public virtual DbSet<DocumentosEvidencias> DocumentosEvidencias { get; set; }
        public virtual DbSet<ObtenerFormularioAvaladoTiempo> ObtenerFormularioAvaladoTiempo { get; set; }
        public virtual DbSet<FORMULARIO_SOLICITUD_TAREAS> FORMULARIO_SOLICITUD_TAREAS { get; set; }
        public virtual DbSet<SolicitudTareaPersona> SolicitudTareaPersona { get; set; }
        public virtual DbSet<EvidenciasFuncionario> EvidenciasFuncionario { get; set; }
    }
}
