//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObtenerFormularioAvaladoTiempo
    {
        public string Email { get; set; }
        public string Motivo { get; set; }
        public int idSolicitud { get; set; }
        public int idFormularioAvalado { get; set; }
    }
}
