//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS
    {
        public int idPago { get; set; }
        public int idFormularioPago { get; set; }
        public int idTipoPago { get; set; }
        public string Monto { get; set; }
    
        public virtual FORMULARIOS_PAGO FORMULARIOS_PAGO { get; set; }
        public virtual TIPOSPAGO TIPOSPAGO { get; set; }
    }
}
