//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAS()
        {
            this.SOLICITUD_TAREAS = new HashSet<SOLICITUD_TAREAS>();
            this.FORMULARIO_SOLICITUD_TAREAS = new HashSet<FORMULARIO_SOLICITUD_TAREAS>();
        }
    
        public int idPersona { get; set; }
        public string NombreCompleto { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public int idDepartamento { get; set; }
    
        public virtual DEPARTAMENTOS DEPARTAMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_TAREAS> SOLICITUD_TAREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMULARIO_SOLICITUD_TAREAS> FORMULARIO_SOLICITUD_TAREAS { get; set; }
    }
}
