//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_TAREAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD_TAREAS()
        {
            this.EVIDENCIAS = new HashSet<EVIDENCIAS>();
            this.FORMULARIOS_AVALADOS = new HashSet<FORMULARIOS_AVALADOS>();
        }
    
        public int idSolicitud { get; set; }
        public int idPersona { get; set; }
        public string Motivo { get; set; }
        public System.DateTime Entrada { get; set; }
        public System.DateTime Salida { get; set; }
        public int TotalHoras { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVIDENCIAS> EVIDENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMULARIOS_AVALADOS> FORMULARIOS_AVALADOS { get; set; }
        public virtual PERSONAS PERSONAS { get; set; }
    }
}
