//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_TAREAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD_TAREAS()
        {
            this.EVIDENCIAS = new HashSet<EVIDENCIAS>();
            this.FORMULARIOS_AVALADOS = new HashSet<FORMULARIOS_AVALADOS>();
        }
    
        public int idSolicitud { get; set; }
        public int idPersona { get; set; }
        public string Motivo { get; set; }
        public System.DateTime Entrada { get; set; }
        public System.DateTime Salida { get; set; }
        public int TotalHoras { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVIDENCIAS> EVIDENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMULARIOS_AVALADOS> FORMULARIOS_AVALADOS { get; set; }
        public virtual PERSONAS PERSONAS { get; set; }
    }
}
