//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaPersona
    {
        public string Email { get; set; }
        public string NombreCompleto { get; set; }
        public int idSolicitud { get; set; }
        public string Motivo { get; set; }
        public System.DateTime Entrada { get; set; }
        public System.DateTime Salida { get; set; }
        public int TotalHoras { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estado { get; set; }
    }
}
